version = 1

[common]
# API mode, set to true to prevent loading local subscriptions or serving local files directly
api_mode = false

# ä¸è¦éšæ„æ”¹å˜å…³é”®å­—ï¼Œå¦åˆ™ä¼šå¯¼è‡´å‡ºé”™
# acl4SSRè§„åˆ™
# å»å¹¿å‘Šï¼šæ”¯æŒ
# è‡ªåŠ¨æµ‹é€Ÿï¼šæ”¯æŒ
# å¾®è½¯åˆ†æµï¼šæ”¯æŒ
# è‹¹æœåˆ†æµï¼šæ”¯æŒ
# å¢å¼ºä¸­å›½IPæ®µï¼šæ”¯æŒ
# å¢å¼ºå›½å¤–GFWï¼šæ”¯æŒ

[emojis]
remove_old_emoji = false

[ruleset]
# Enable generating rules with rulesets
enabled = true
# Overwrite the existing rules in rule_base
overwrite_original_rules = false
# Perform a ruleset update on request
update_ruleset_on_request = false

# è®¾ç½®è§„åˆ™æ ‡å¿—ä½ - æ¯ä¸ªè§„åˆ™é›†å¿…é¡»å•ç‹¬å®šä¹‰
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"

[[rulesets]]
group = "ğŸƒ åº”ç”¨å‡€åŒ–"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCNProxyIP.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯Bing"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ¤– Claude"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ClaudeAI.list"

[[rulesets]]
group = "ğŸ¤– Claude"
ruleset = "[]GEOSITE,anthropic"

[[rulesets]]
group = "âœ¨ Gemini"
ruleset = "https://raw.githubusercontent.com/Passerby1011/Garbage-dump/refs/heads/main/Gemini.list"

[[rulesets]]
group = "ğŸ’¬ OpenAi"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "[]GEOSITE,steam"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "[]GEOSITE,category-games"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"

[[rulesets]]
group = "ğŸ¦ Twitter"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Twitter.list"

[[rulesets]]
group = "ğŸ¸ Spotify"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Spotify.list"

[[rulesets]]
group = "ğŸ¶ Tiktok"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/TikTok.list"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"

[[rulesets]]
group = "ğŸ” é­…åŠ›è‰ºæœ¯"
ruleset = "https://raw.githubusercontent.com/Passerby1011/Garbage-dump/refs/heads/main/PH.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOSITE,gfw"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list,28800"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/IPTVMainland_Domain.list,28800"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "clash-domain:https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOSITE,cn"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "clash-ipcidr:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt,no-resolve"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,no-resolve"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

# è®¾ç½®åˆ†ç»„æ ‡å¿—ä½ - æ¯ä¸ªè‡ªå®šä¹‰ç»„å¿…é¡»å•ç‹¬å®šä¹‰
[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡", "[]DIRECT"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = ["(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|ğŸ‡­ğŸ‡°|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|UnitedStates|America|ğŸ‡ºğŸ‡¸|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|ğŸ‡¹ğŸ‡¼|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“|ğŸ‡°ğŸ‡·)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ¤– Claude"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "âœ¨ Gemini"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡", "[]DIRECT"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯Bing"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ¦ Twitter"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]DIRECT", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ¸ Spotify"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]DIRECT", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ¶ Tiktok"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ›– å®¶å®½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]DIRECT", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ å…¶ä»–èŠ‚ç‚¹-æ‰‹åŠ¨", "[]ğŸ³ï¸â€ğŸŒˆç‰¹æ®Šå€ç‡èŠ‚ç‚¹", "[]ğŸ’¦è´Ÿè½½å‡è¡¡"]

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["[]ğŸ¥ å¥ˆé£èŠ‚ç‚¹", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹-è‡ªåŠ¨", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
